services:
  backend:
    image: meeting-api
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/meeting-app

  frontend:
    image: meeting-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    env_file:
      - ./frontend/.env

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
