FROM node:18.15.0-alpine3.17

ENV NODE_ENV=production

WORKDIR /app

ADD package.json package-lock.json ./

RUN npm install --production --ignore-scripts

ADD bin ./bin
ADD src ./src

CMD [ "npm", "start" ]
